# Generated by Django 4.2.6 on 2023-11-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
