# Generated by Django 4.2.6 on 2023-11-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
